brew "node"
brew "ffmpeg"
brew "fzf"
brew "delta"
brew "gh"
brew "jq"
brew "luarocks"
brew "neovim"
brew "railway"
brew "ripgrep"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "font-blex-mono-nerd-font"
cask "ghostty"
cask "karabiner-elements"
