-- vim.pack.add({
--         { src = "https://github.com/nvim-lua/plenary.nvim" },
--         { src = "https://github.com/nvim-telescope/telescope.nvim" },
--         { src = "https://github.com/nvim-telescope/telescope-ui-select.nvim" },
--         { src = "https://github.com/nvim-telescope/telescope-github.nvim" },
--         { src = "https://github.com/debugloop/telescope-undo.nvim" },
-- })
--
-- local telescope = require("telescope")
--
-- telescope.setup({
--         extensions = {
--                 ['ui-select'] = {
--                         require('telescope.themes').get_dropdown(),
--                 },
--         },
--
-- })
--
-- telescope.load_extension("ui-select")
--
-- local builtin = require('telescope.builtin')
--
-- vim.keymap.set('n', '<D-p>', builtin.find_files)
--
-- vim.keymap.set('n', '<leader>sh', builtin.help_tags, { desc = 'Search help' })
-- vim.keymap.set('n', '<leader>sk', builtin.keymaps, { desc = 'Search keymaps' })
-- vim.keymap.set('n', '<leader>ss', builtin.builtin, { desc = 'Search Select Telescope' })
-- vim.keymap.set('n', '<leader>sw', builtin.grep_string, { desc = 'Search current word' })
-- vim.keymap.set('n', '<leader>sg', builtin.live_grep, { desc = 'Search by grep' })
-- vim.keymap.set('n', '<leader>sd', builtin.diagnostics, { desc = 'Search diagnostics' })
-- vim.keymap.set('n', '<leader>sr', builtin.resume, { desc = 'Search resume' })
-- vim.keymap.set('n', '<leader>s.', builtin.oldfiles, { desc = 'Search recent files ("." for repeat)' })
-- vim.keymap.set('n', '<leader><leader>', builtin.buffers, { desc = 'Find existing buffers' })
--
-- vim.keymap.set('n', '<leader>/', function()
--         -- You can pass additional configuration to Telescope to change the theme, layout, etc.
--         builtin.current_buffer_fuzzy_find(require('telescope.themes').get_dropdown {
--                 winblend = 10,
--                 previewer = false,
--         })
-- end, { desc = '[/] Fuzzily search in current buffer' })
--
-- vim.keymap.set('n', '<leader>s/', function()
--         builtin.live_grep {
--                 grep_open_files = true,
--                 prompt_title = 'Live Grep in Open Files',
--         }
-- end, { desc = '[S]earch [/] in Open Files' })
--
-- telescope.load_extension("undo")
-- vim.keymap.set('n', '<leader>su', function()
--         telescope.extensions.undo.undo()
-- end
-- , { desc = 'Search undo history' })
--
-- telescope.load_extension("gh")
--
-- vim.keymap.set("n", "<leader>ghi", function()
--         telescope.extensions.gh.issues()
-- end, { noremap = true, silent = true, desc = "GitHub issues" })
--
-- vim.keymap.set("n", "<leader>ghp", function()
--         telescope.extensions.gh.pull_request()
-- end, { noremap = true, silent = true, desc = "GitHub PRs" })
